name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]


jobs:
  simple_deployment_pipeline:
    name: Lint, Run Tests, and Deploy to Heroku
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install 
        run: npm install  
      - name: lint        
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with: 
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: deploy to heroku
        if: "!contains(toJSON(github.event.commits.*.message), '#skip')"
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "part11-pokedex-app"
          heroku_email: "nicholas.cruickshank25@gmail.com"
          healthcheck: "https://part11-pokedex-app.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
      - name: Bump Version and Push Tag
        if: "github.event_name == 'push' && !contains(toJSON(github.event.commits.*.message), '#skip')"
        with:
          fetch-depth: '0'
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
      - name: Success Slack Message
        if: ${{ github.event_name == 'push' && !contains(toJSON(github.event.commits.*.message), '#skip') && success() }}
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with: 
          status: custom
          fields: commit, author, took
          custom_payload: |
            {
              attachments: [{
                color: 'good',
                text: `A new version deployed to https://part11-pokedex-app.herokuapp.com/ (${process.env.AS_COMMIT}) by ${process.env.AS_AUTHOR} build took ${process.env.AS_TOOK}`,
              }]
            }
      - name: Error Slack Message
        if: ${{ github.event_name == 'push' && !contains(toJSON(github.event.commits.*.message), '#skip') && failure() }}
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          fields: repo, message, commit, author, took

